### ISSUE TITLE
Release to [maven central] repository?

### ISSUE THREAD

**Issue by mmoayyed** [banichols/jsqrl-server#8]
Hello,

Thanks for the awesomeness here. Great work. May I ask that you release the server impl here into some sort of central repository so it can be shared with others more easily? The sample app that is provided currently does require that one build the server from scratch and install it locally.

**Comment by banichols** [comment]
Thanks for the feedback. I've released the code as is and published version 0.1.0 to Maven Central (https://repo1.maven.org/maven2/org/jsqrl/jsqrl-server/0.1.0/ ).

Note that the current code may not completely comply with all the latest SQRL V1 protocol updates. I will update this library after Steve Gibson has declared he's done making changes.

**Comment by mmoayyed** [comment]
Thank you. Great work. 

Could I also ask you, do you happen to have a good client handy for Mac OS and/or android for testing? I have the SQRL android app running and and it always seems to fail after the initial QR scan. Not too familiar with the protocol myself, I suspect it's because the app cant POST to localhost:8080?

Same sort of situation with the native Mac OS client: https://sqrlid.com/beta

What client would you recommend to test the current functionality?

**Comment by banichols** [comment]
It is possible to test hitting 127.0.0.1, I previously did a lot of testing using the Windows reference client hitting qrl://127.0.0.1:8080. Some clients may be enforcing TLS (sqrl instead of qrl), which would be a little more involved to get working locally. I can't say that I've tried any Android or OSX clients.

Either way, it looks like the SQRL semantics have changed since I last worked on this project and this sample app is no longer working with the reference Windows client, and I imagine other clients will have the same issue. If you want to test a client in the mean time you can try hitting Steve's demo at https://www.grc.com/sqrl/demo.htm

I'll try to find some time in the coming weeks to get this project updated with the latest SQRL changes. Thanks for your interest!

**Comment by mmoayyed** [comment]
Yup. The official windows client seems to be sitting on `localhost:25519` as is demonstrated here: https://www.grc.com/sqrl/demo/pagesync.js; It no longer responds to `qrl` or `sqrl` protocol requests. The client I have been using on Mac however does respond. 

The problem with the demo instance or any other client for that matter is that they are extremely unhelpful in producing error messages that one can use to diagnose errors. For instance, the Android client that I have (and this is true for the windows client and the mac client) recognizes the QR code, asks for confirmation and attempts to then make that secure POST back to the application. I can see the Controller does respond successfully with a 200 status code. Then the client app simply says "sorry something went wrong" and there is no way to figure out what happened and how. From the server perspective, everything looks normal. 

I am working to see if SQRL can be supported in CAS: https://github.com/apereo/cas/issues/2401 if you need help from me testing things, please let me know.
